### ISSUE TITLE
rosdep migration to groovy needs a standard procedure  (ros ticket #4018)

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/rosdep#202]
Vincent's quick solution was to remove the sources.list and rerun rosdep init.

trac data:
- Owner: **tfoote**
- Reporter: **tfoote**
- Reported at: **Tue Jul 24 17:49:25 2012**
- URL: http://code.ros.org/trac/ros/ticket/4018

**Comment by Lome789** [comment]
ew...the URL is useless now...
