### ISSUE TITLE
rosdep add support for virtual packages

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/rosdep#274]
Issues like https://github.com/ros/rosdistro/pull/2100 suggest that it might be useful for rosdep to support OR logic such that it can be resolved by A OR B packages. Or to directly support virtual packages.  

I'm not sure how to use apt exactly to do this.  

Also adding this capability needs to be reviewed carefully to make sure that installations remain deterministically reliable.

**Comment by ipa-mdl** [comment]
This was fixed in #468.  I have tried it with the `linux-kernel-headers` packages introduced in https://github.com/ros/rosdistro/pull/15064

**Comment by tfoote** [comment]
@ipa-mdl thanks for the followup!

**Comment by tfoote** [comment]
I'm reopening this since we have resolved the checking in #468 but from testing on https://github.com/ros/rosdistro/pull/15308 we can't install virtual packages.

**Comment by ipa-mdl** [comment]
My bad, `linux-kernel-headers` seems to work because it has only one candidate.
