### ISSUE TITLE
OS X source build complains about homebrew

### ISSUE THREAD

**Issue by adamfowleruk** [ros-infrastructure/rosdep#286]
When executing rosdep on 10.9 mavericks with hydro using the desktop-full package I get this:-
adam-mac:ros_catkin_ws adamfowler$ sudo rosdep install --from-paths src --ignore-src --rosdistro hydro -y
Password:

ERROR: Rosdep experienced an internal error.
Please go to the rosdep page [1] and file a bug report with the message below.
[1] : http://www.ros.org/wiki/rosdep

rosdep version: 0.10.24

Bad installer [homebrew]: [Errno 2] No such file or directory

adam-mac:ros_catkin_ws adamfowler$

I do not have homebrew installed, but I fail to see why I need it? I use macports and given ROS documentation mentions both homebrew and macports I assumed rosdep would recognise either and use the appropriate one, or would at least fail and let e now the packages I needed to install manually.

Is there a setting somewhere to instruct rosdep to use macports? Is this checking for macports (if it exists) failing?

**Comment by wjwwood** [comment]
I'm going to close this since some path forward was suggested. Feel free to continue discussing this here.
