### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by richmattes** [ros-infrastructure/rosdep#29]
Please add a LICENSE file with the BSD license text to rosdep's source tree.

**Comment by 130s** [comment]
I might be mistaken, but does the LICENSE file added in https://github.com/ros-infrastructure/rosdep/commit/7b42d5e936165dd41197652b0621b3edec4fe82a declare any license? I do see in [setup.py BSD is declared](https://github.com/ros-infrastructure/rosdep/blob/30a631fabcafa7238fac34905f998e5f7bda918e/setup.py#L25).

**Comment by tfoote** [comment]
It doesn't need to declare the license it is the BSD license.
