### ISSUE TITLE
OS X Homebrew: Boost should be installed with `--with-python`

### ISSUE THREAD

**Issue by NikolausDemmel** [ros-infrastructure/rosdep#330]
Homebrew [doesn't build Boost.Python by default any more](https://github.com/Homebrew/homebrew/commit/4bf4ee77fa858bb5e56406504cf86564bd5ece3d). We would need to install boost with `brew install boost --with-python`. Boost.Python is used (at least) by `cv_brigde`, so builds including that of people with upgraded boost should fail.

Maybe we need to get #304 ready to be merged at last.

**Comment by jeromekimbrough** [comment]
Is there an update for macOS 10.14? `brew install boost --with-python` does not work, nor does `brew install boost-python`.
