### ISSUE TITLE
rosdep install fails on osx indigo

### ISSUE THREAD

**Issue by jmtatsch** [ros-infrastructure/rosdep#339]
```
~/ros_catkin_ws » rosdep install --from-paths src --ignore-src --rosdistro indigo -y
ERROR: Rosdep experienced an internal error.
Please go to the rosdep page [1] and file a bug report with the message below.
[1] : http://www.ros.org/wiki/rosdep

rosdep version: 0.10.30

Bad installer [homebrew]: Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/rosdep2/platforms/osx.py", line 182, in is_installed
    pkg_info = json.loads(std_out)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by jmtatsch** [comment]
Now the same thing with jade, repairing the taps did not help.

rosdep install --from-paths src --ignore-src --rosdistro jade -y                                                                                       

ERROR: Rosdep experienced an internal error.
Please go to the rosdep page [1] and file a bug report with the message below.
[1] : http://www.ros.org/wiki/rosdep

rosdep version: 0.11.2

Bad installer [homebrew]: Error while parsing brew info for 'pcl'
 * Output of `brew info pcl --json=v1`:
 
 * Error while parsing:
 Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/rosdep2/platforms/osx.py", line 184, in is_installed
    pkg_info = json.loads(std_out)
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by jmtatsch** [comment]
brew info pcl --json=v1                                                                                                                                
Error: Formulae found in multiple taps: 
 * homebrew/science/pcl
 * ros/deps/pcl

Please use the fully-qualified name e.g. homebrew/science/pcl to refer the formula.

**Comment by wjwwood** [comment]
@jmtatsch thanks for digging into the issue, can you open a pull request against ros/rosdistro to change the rule to use the `homebrew/science/pcl` instead of just `pcl`?

**Comment by zacwitte** [comment]
I'm having a similar problem with rosdep

```
rosdep install --from-paths src --ignore-src --rosdistro indigo -y

ERROR: Rosdep experienced an internal error.
Please go to the rosdep page [1] and file a bug report with the message below.
[1] : http://www.ros.org/wiki/rosdep

rosdep version: 0.11.4

Bad installer [pip]: [Errno 2] No such file or directory
```

**Comment by 812406210** [comment]
I have a issue,can you help me to resovel
*****************************************************************************
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies (ROS distro is not set. Make sure `ROS_DISTRO` environment variable is set, or use `--rosdistro` option to specify the distro, e.g. `--rosdistro indigo`):
cartographer_ros_msgs: Cannot locate rosdep definition for [geometry_msgs]
cartographer: Cannot locate rosdep definition for [catkin]
cartographer_ros: Cannot locate rosdep definition for [rosunit]
cartographer_rviz: Cannot locate rosdep definition for [rviz]
ceres-solver: Cannot locate rosdep definition for [catkin]
**********************************************************************************
i can't  resovel it

**Comment by tfoote** [comment]
@812406210 please ask for help on http://answers.ros.org following our [Support policy](http://wiki.ros.org/Support). Your question is unrelated to this thread.

**Comment by wjwwood** [comment]
Closing for now, I can reopen if anyone thinks it should be.
