### ISSUE TITLE
rosdep can't install libvtk-java on osx Yosemite

### ISSUE THREAD

**Issue by jmtatsch** [ros-infrastructure/rosdep#355]
rosdep install --from-paths src --ignore-src --rosdistro indigo -y
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
pcl_ros: No definition of [libvtk-java] for OS [osx]
---
or should that better be filed at pcl_ros?

**Comment by wjwwood** [comment]
I believe this has been resolved: https://github.com/ros/rosdistro/blob/754e8d23f5c30c05a7e23600218064fda48d4ff9/rosdep/osx-homebrew.yaml#L345-348
