### ISSUE TITLE
Gentoo USE flags are not automatically satisfied

### ISSUE THREAD

**Issue by allenh1** [ros-infrastructure/rosdep#387]
Portage has a wonderful tool for automatically satisfying USE flags. If you add the flag "--autounmask-write" to an emerge command, then the proper USE flags will be established for the packages you desire. After running emerge with this command, however, one must run "etc-update" to perform the modifications, then one re-runs emerge to begin the actual emerge process. This would greatly simplify the process for Gentoo users, and would make Gentoo installs more Ubuntu-like with respect to rosdep.

**Comment by wjwwood** [comment]
I'm not sure what exactly you're asking us to change. Please propose a pull request with a clear description of what's changing and I'll give it a review.

**Comment by allenh1** [comment]
Will do.

**Comment by allenh1** [comment]
I've decided against this. It's not a good idea to automatically modify use flags like that... I think I'll just make a note about handling it with the installation instructions.
