### ISSUE TITLE
Homebrew/homebrew Error: Operation already in progress for protobuf 

### ISSUE THREAD

**Issue by mzaiady** [ros-infrastructure/rosdep#407]
On Mac OSX:10.10.5

$rosdep install --from-paths src --ignore-src --rosdistro indigo -y

executing command [brew install gazebo]
==> Installing gazebo from osrf/homebrew-simulation
Error: Operation already in progress for protobuf
Another active Homebrew process is already using protobuf.
Please wait for it to finish or terminate it to continue.
ERROR: the following rosdeps failed to install
homebrew: command [brew install gazebo] failed

No other Homebrew running, I did restart the machine , but still the same result!

A comment in the Homebrew/homebrew#43520 suggests that it this could happen if a tap has a formula that duplicates the name of a formula in core.

How to proceed with ros installation?

**Comment by wjwwood** [comment]
Please comment on the closed issue, do not open new issues. I can reopen the original issue if necessary.

**Comment by mzaiady** [comment]
thank you
