### ISSUE TITLE
Add El Capitan to supported OS X Versions

### ISSUE THREAD

**Issue by owltheory** [ros-infrastructure/rosdep#409]
The `rosdep update` command of step 1.3 on [the homebrew installation for OS X](http://wiki.ros.org/jade/Installation/OSX/Homebrew/Source) will fail on El Capitan.

All that needs to be done is to change the list defined in rospkg/os_detect.py:

```python
223 _osx_codename_map = {4: 'tiger',
224                      5: 'leopard',
225                      6: 'snow',
226                      7: 'lion',
227                      8: 'mountain lion',
228                      9: 'mavericks',
229                      10: 'yosemite',
230                      11: 'el capitan'} # add this line
```

Will report back if this breaks other things.

**Comment by wjwwood** [comment]
Thanks for reporting this, but please open a pull request to this affect on the `rospkg` issue tracker: https://github.com/ros-infrastructure/rospkg/issues
