### ISSUE TITLE
unable to resolve dep Bad installer [pip]:.......

### ISSUE THREAD

**Issue by Lome789** [ros-infrastructure/rosdep#414]
When i input       rosdep install --from-paths src --ignore-src --rosdistro jade   
it shows
 ERROR: Rosdep experienced an internal error.
Please go to the rosdep page [1] and file a bug report with the message below.
[1] : http://www.ros.org/wiki/rosdep

rosdep version: 0.11.3

Bad installer [pip]: Command '['pip', 'show', 'nose']' returned non-zero exit status 1

**Comment by wjwwood** [comment]
This may be related to https://github.com/ros-infrastructure/rosdep/pull/413

**Comment by wjwwood** [comment]
I can reproduce this, I have proposed https://github.com/ros-infrastructure/rosdep/pull/415 as a fix.

**Comment by Lome789** [comment]
Sorry  .... Actually i have no idea about how to fix it with ur method.. i am a complete newbie..

**Comment by wjwwood** [comment]
@Lome789 that's ok, I'm going to make a new release asap and then you can just update rosdep and try again. I'm just making sure the fix is good.

**Comment by Lome789** [comment]
Thanks a lot!

**Comment by wjwwood** [comment]
Ok, `0.11.4` should be out now, so you can update `rosdep` and try what ever you were doing again.

You can check your `rosdep` version like this:

```
% rosdep --version
0.11.4
```

**Comment by wkentaro** [comment]
@wjwwood
Thanks. That works in my environment.

**Comment by Lome789** [comment]
No matter how many times i updated rosdep it was still 0.11.3 
i have ran sudo rosdep update once maybe it would cause problem?

**Comment by wkentaro** [comment]
I think I don't understand what you mean with sudo rosdep update, but the problem of this issue will be resolved after you upgrade rosdep to 0.11.4.

**Comment by Lome789** [comment]
yeah ...unfortunately i can't upgrade to 0.11.4

**Comment by wkentaro** [comment]
rosdep for apt is not yet released.
maybe you should wait for it, or remove apt package and install via pip.

2015年9月26日土曜日、Lome789<notifications@github.com>さんは書きました:

> yeah ...unfortunately i can't upgrade to 0.11.4
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ros-infrastructure/rosdep/issues/414#issuecomment-143438937>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Comment by Lome789** [comment]
ok..thank u so much!

**Comment by tfoote** [comment]
0.11.4 is available via debian package

**Comment by Lome789** [comment]
In OS X how to achieve this update?

**Comment by wkentaro** [comment]
```
$ pip install --upgrade rosdep
$ rosdep --version
```

**Comment by Lome789** [comment]
ew...i gonna try to find other related issues... 

$ pip install --upgrade rosdep
Collecting rosdep
  Using cached rosdep-0.11.4.tar.gz
Requirement already up-to-date: catkin-pkg in /Library/Python/2.7/site-packages (from rosdep)
Requirement already up-to-date: rospkg>=1.0.34 in /Library/Python/2.7/site-packages (from rosdep)
Requirement already up-to-date: rosdistro>=0.4.0 in /Library/Python/2.7/site-packages (from rosdep)
Requirement already up-to-date: PyYAML>=3.1 in /Library/Python/2.7/site-packages (from rosdep)
Requirement already up-to-date: argparse in /Library/Python/2.7/site-packages (from catkin-pkg->rosdep)
Requirement already up-to-date: docutils in /Library/Python/2.7/site-packages (from catkin-pkg->rosdep)
Requirement already up-to-date: python-dateutil in /Library/Python/2.7/site-packages (from catkin-pkg->rosdep)
Requirement already up-to-date: setuptools in /Library/Python/2.7/site-packages (from rosdistro>=0.4.0->rosdep)
Requirement already up-to-date: six>=1.5 in /Library/Python/2.7/site-packages (from python-dateutil->catkin-pkg->rosdep)
Installing collected packages: rosdep
  Found existing installation: rosdep 0.11.3
    Uninstalling rosdep-0.11.3:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/commands/install.py", line 311, in run
    root=options.root_path,
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/req/req_set.py", line 640, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/req/req_install.py", line 716, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/req/req_uninstall.py", line 125, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/utils/__init__.py", line 315, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 300, in move
    rmtree(src)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 250, in rmtree
    os.remove(fullname)
OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/rosdep-0.11.3-py2.7.egg-info/dependency_links.txt'

**Comment by wkentaro** [comment]
sudo ?

**Comment by Lome789** [comment]
yeah it works!!!thanks a lot!!!
