### ISSUE TITLE
rosdeps failed to install & failure /usr/bin/patch -g 0 -f -p1

### ISSUE THREAD

**Issue by Lome789** [ros-infrastructure/rosdep#418]
I wanted to resolve dependencies and Error: No available formula for homebrew/dupes/tcl-tk  occured at once but it still downloaded files for morethan 1.5hours, finally it went wrong.  is the problem relate to Homebrew?

ros_catkin_ws Lome$ rosdep install --from-paths src --ignore-src --rosdistro jade -y
Error: No available formula for homebrew/dupes/tcl-tk 
Please tap it and then try again: brew tap homebrew/dupes
executing command [brew install homebrew/science/pcl --HEAD]
==> Installing pcl from homebrew/homebrew-science
==> Cloning https://github.com/PointCloudLibrary/pcl.git
Updating /Library/Caches/Homebrew/pcl--git
==> Checking out branch master
==> Patching
patching file cmake/pcl_find_cuda.cmake
Hunk #1 FAILED at 1.
Hunk #2 FAILED at 37.
2 out of 2 hunks FAILED -- saving rejects to file cmake/pcl_find_cuda.cmake.rej
Error: Failure while executing: /usr/bin/patch -g 0 -f -p1
ERROR: the following rosdeps failed to install
  homebrew: command [brew install homebrew/science/pcl --HEAD] failed

**Comment by wjwwood** [comment]
This doesn't have anything to do with `rosdep`. This command failed `brew install homebrew/science/pcl --HEAD`. You can run it without running rosdep. Please file an issue against homebrew-science for the PCL formula.
