### ISSUE TITLE
rosdep update error: unable to handle 'index' format version '3'

### ISSUE THREAD

**Issue by eshwaryr** [ros-infrastructure/rosdep#447]
I'm trying to install ros hydro on udoo. But I'm facing problem with rosdep update. It gives the following error.

reading in sources list data from /etc/ros/rosdep/sources.list.d 
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/osx-homebrew.yaml 
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/base.yaml 
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/python.yaml 
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/ruby.yaml 
Hit https://raw.githubusercontent.com/ros/rosdistro/master/releases/fuerte.yaml 
Query rosdistro index https://raw.github.com/ros/rosdistro/master/index.yaml

    ERROR: Rosdep experienced an error: Unable to handle 'index' format version '3', please update rosdistro (e.g. on Ubuntu/Debian use: sudo apt-get update && sudo apt-get install
    --only-upgrade python-rosdistro) Please go to the rosdep page [1] and file a bug report with the stack trace below. [1] : http://www.ros.org/wiki/rosdep

    rosdep version: 0.10.30

    Traceback (most recent call last):   File "/usr/lib/pymodules/python2.7/rosdep2/main.py", line 126, in rosdep_main
        exit_code = _rosdep_main(args)   File "/usr/lib/pymodules/python2.7/rosdep2/main.py", line 286, in _rosdep_main
        return _no_args_handler(command, parser, options, args)   File "/usr/lib/pymodules/python2.7/rosdep2/main.py", line 294, in _no_args_handler
        return command_handlers[command](options)   File "/usr/lib/pymodules/python2.7/rosdep2/main.py", line 468, in command_update
        error_handler=update_error_handler)   File "/usr/lib/pymodules/python2.7/rosdep2/sources_list.py", line 433, in update_sources_list
        for dist_name in sorted(get_index().distributions.keys()): File "/usr/lib/pymodules/python2.7/rosdep2/rosdistrohelper.py", line 69, in get_index
        _RDCache.index = rosdistro.get_index(_RDCache.index_url) File "/usr/lib/pymodules/python2.7/rosdistro/__init__.py", line 115, in get_index
        return Index(data, base_url)   File "/usr/lib/pymodules/python2.7/rosdistro/index.py", line 51, in __init__
        assert int(data['version']) == 2, "Unable to handle '%s' format version '%d', please update rosdistro (e.g. on Ubuntu/Debian use: sudo apt-get update && sudo apt-get install --only-upgrade python-rosdistro)" % (Index._type, int(data['version'])) AssertionError: Unable to handle 'index' format version '3', please update rosdistro (e.g. on Ubuntu/Debian use: sudo apt-get update && sudo apt-get install
    --only-upgrade python-rosdistro)

I have even tried apt-get install --only-upgrade but of no use
Then i tried pip but was unable to successfully install rosdep or rosdistro. 
I have been stuck here for days
Any idea on how to solve this issue? It would be of great help

**Comment by wjwwood** [comment]
http://answers.ros.org/question/122266/how-can-i-fix-unable-to-handle-index-format-version-2-please-update-rosdistro/
