### ISSUE TITLE
pip cannot fetch rosdep 

### ISSUE THREAD

**Issue by Thezkiller** [ros-infrastructure/rosdep#467]
Recently i want to install ros in my beaglebone.my system is debian Wheezy.
and i try this :
#pip install -U rosdep rosinstall_generator wstool rosinstall
but comes:
#cannot fetch index base URL http://pypi.python.org/simple/
....
i really hope anyone can help me.i was really confused. my pip version is 1.1 python 2.7

**Comment by tfoote** [comment]
pip 1.1 is very old, circa 2012 I doubt that pypi the service is continuing to use the same urls etc. For example the provided link is now a 301 to the https version.

There also may have been a network issue either locally or pypi end. But this is not a rosdep issue so I'm going to close this issue.
