### ISSUE TITLE
Error with sudo rosdep init 

### ISSUE THREAD

**Issue by sigmorew** [ros-infrastructure/rosdep#492]
I get this error when I put in that command, 
ERROR: cannot download default sources list from:
https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/sources.list.d/20-default.list
Website may be down.

Any ideas?

**Comment by tfoote** [comment]
As from the error message "Website may be down" suggests that either when you tried github was down or you don't have internet connectivity.  Please take a look on http://answers.ros.org for others having this issue and if you're still having problem ask a new question. But when you do link to the other questions with solutions you've tried so people answering know that it's not just a duplicate question.
