### ISSUE TITLE
webkit_dependency: No definition of [python-qt-bindings-webkit] for OS [gentoo] 

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [ros-infrastructure/rosdep#517]
running `rosdep install --from-paths src --ignore-src --rosdistro jade -y` on gentoo
gives me
webkit_dependency: No definition of [python-qt-bindings-webkit] for OS [gentoo]

see https://github.com/ros/ros-overlay/issues/28

**Comment by mikaelarguedas** [comment]
Thanks for reporting it, can you submit a PR on https://github.com/ros/rosdistro/blob/master/rosdep/python.yaml#L2111 to add the missing package rule?

**Comment by tfoote** [comment]
@Alessandro-Barbieri There's a guide to submitting rosdep rules here: http://docs.ros.org/independent/api/rosdep/html/contributing_rules.html I'm going to close this here. 

@allenh1 FYI.
