### ISSUE TITLE
Can't choose whether or not to install pip2 or pip3 version of pip package

### ISSUE THREAD

**Issue by jlack1987** [ros-infrastructure/rosdep#519]
Have run into the case where I need a specific version of a pip package, but it looks like the in the rosdep yaml files rosdep is not setup to look explicitly for either `pip2` or `pip3` and instead just looks for `pip` and uses whatever version the `pip` executable is using. It would be awesome if we could explicitly say a key should be installed with `pip2 ` or `pip3`

**Comment by wjwwood** [comment]
Sounds good to me. I don't have time to look into it myself, but I'll try to review and release a pr that adds a `pip3` installer.

**Comment by willcbaker** [comment]
agreed; can't use rosdep if you have pip3 installed. lame

**Comment by willcbaker** [comment]
@wjwwood any comment on how best to implement this? I added a test-passing pip2/pip3 installer but am unaware of how to run the tests locally

**Comment by wjwwood** [comment]
I would drop the `pip` generic installer and invoke pip via python, i.e. `python2 -m pip ...` or `python3 -m pip ...`, where appropriate.

**Comment by mikepurvis** [comment]
I agree with that direction, but note that it gets hairy on OS X, as homebrew now installs its brewed pythons as `python2` and `python3`, leaving the system python as `python`.

I'm not sure what the best way out of this is, except that there need to be multiple ways to override which python is used to invoke `pip`.

**Comment by PymZoR** [comment]
As I read http://wiki.ros.org/UsingPython3/IdentifyDependencies, in particular the example on how to add Python3 packages rosdep key (https://github.com/ros/rosdistro/pull/21800), I wondered how to add `pip3` dependencies. 

As Noetic is coming and support for Python3 packages can be quite limited if only `pip` and system package managers are available on rosdep, is the `pip3` installer support considered ?

**Comment by tfoote** [comment]
With the new ROS_PYTHON_VERSION definitions in [REP 149](https://www.ros.org/reps/rep-0149.html) I think that it makes sense that all the pip rules should resolve to pip3 for noetic by default unless the user sets ROS_PYTHON_VERSION manually. In which case the pip installer will use the user's chosen version.  #709 is going in that direction.
