### ISSUE TITLE
v0.11.7 breaks rosdep for meta-packages

### ISSUE THREAD

**Issue by ipa-mdl** [ros-infrastructure/rosdep#534]
Looks like #531 was not complete.

rosdep {keys, install} fails with 
```
MY_METAPACKAGE: Missing resource MY_METAPACKAGE
```

I will look into it again.

**Comment by ipa-mdl** [comment]
fixed in #535

**Comment by wjwwood** [comment]
`0.11.8` is out

**Comment by ipa-mdl** [comment]
There is still an issue:
Some of our meta-packages depend on `python-wstool`.
For distros < kinetic it is listed in https://github.com/ros/rosdistro/blob/master/rosdep/python.yaml#L3629 and it works as a fall-back.
For newer distro the key for `python-wstool` gets read from somewhere else, but where?

**Comment by wjwwood** [comment]
> I guess the key needs to be added. We did not discover this yet because meta-packages got skipped.

I guess so, it should be in all the OS's as `python-wstool`. I'll let you open a pr against ros/rosdistro if it's needed.

P.S. prefer a new comment to editing when adding info (we don't get notifications of an edit)
