### ISSUE TITLE
rosdep installation failed with pygraphviz install

### ISSUE THREAD

**Issue by Edith001** [ros-infrastructure/rosdep#550]
Hi I am running rosdep installation like this "rosdep install --from-paths src --ignore-src --rosdistro kinetic -y --skip-keys "libqt5-core libqt5-gui libqt5-opengl libqt5-opengl-dev libqt5-widgets qt5-qmake qtbase5-dev" and returned with  failed while pip install pygraphviz failed.The terminal returns as shown in the picture.
![py](https://user-images.githubusercontent.com/32041148/30525340-a61043ea-9bd2-11e7-8553-3b9f9a96fbf3.jpg)
Could anyone please help me with that?

**Comment by wjwwood** [comment]
Please do not post a picture of text. Update your issue with the text in the error (including more that what is in the picture) and I will try to help.

In general, never, ever, ever post a picture of text. It cannot be searched or copied and pasted.

----

Do you have graphviz installed from homebrew?

**Comment by wjwwood** [comment]
Closing for now, I will reopen this when the original issue is updated.
