### ISSUE TITLE
rosdep version: 0.11.8

### ISSUE THREAD

**Issue by willyclarke** [ros-infrastructure/rosdep#552]
Bad installer [pip]: [Errno 2] No such file or directory

Installed on Mac with High Sierra
-----------------------
Full listing below:
-----------------------
rosdep install --from-paths src --ignore-src --rosdistro kinetic -y

ERROR: Rosdep experienced an internal error.
Please go to the rosdep page [1] and file a bug report with the message below.
[1] : http://www.ros.org/wiki/rosdep

rosdep version: 0.11.8

Bad installer [pip]: [Errno 2] No such file or directory

**Comment by wjwwood** [comment]
Install `pip`: https://pip.pypa.io/en/stable/installing/
