### ISSUE TITLE
Confusing error message dpkg-query: no packages

### ISSUE THREAD

**Issue by nalt** [ros-infrastructure/rosdep#569]
rosdep install prints many messages saying e.g.:

`dpkg-query: no packages found matching ros-kinetic-tf`

This sounds like an error message about a missing package, while it actually only happens during the check whether this package is already installed. This message should be suppressed or explained better.

**Comment by wjwwood** [comment]
What version of rosdep are you using?

**Comment by jbohren-hbr** [comment]
I see the same behavior in version `0.11.8`

**Comment by ipa-mdl** [comment]
I have removed this output in #521

**Comment by wjwwood** [comment]
Closing with #521 merged.
