### ISSUE TITLE
High Sierra Compatibility with brew

### ISSUE THREAD

**Issue by shanemeister** [ros-infrastructure/rosdep#603]
EDIT:
Several of my applications have behaved oddly, in particular, apache-spark and mysql. if I enter `brew services mysql start` I get the same message as I get if I do the same for other applications as well which is: `Error: No available formula with the name "start" ` 

I have uninstalled and reinstalled all of the applications, but have not reinstalled brew. Any ideas?

**Comment by nuclearsandwich** [comment]
This issue appears related to homebrew rather than rosdep. I'd suggest taking a look at the [brew manual page](https://docs.brew.sh/Manpage) and asking a question on the homebrew discourse if you have further difficulty: https://discourse.brew.sh/
