### ISSUE TITLE
rosdep install Error: No available formula with the name "dartsim/dart/fcl" 

### ISSUE THREAD

**Issue by robotdreamers** [ros-infrastructure/rosdep#624]
My system: MacOS High Sierra, Melodic ROS, python 2.7.5, gazebo8

I am installing moveit using instruction in this website: No available formula with the name `dartsim/dart/fcl`

When running: `rosdep install -y --from-paths src --ignore-src --rosdistro melodic`

I got the following error: `Error: No available formula with the name "dartsim/dart/fcl"`
caused by command: `brew info dartsim/dart/fcl --json=v1`

I check brew, it only has  dartsim/dart/fcl03 and dartsim/dart/fcl04. Tried to install either of this, but rosdep still failed because it is looking for `dartsim/dart/fcl` which does not exist anymore.
I tried to look for the configuration files that may specify this dependency but failed to do so.

Anyone have any idea how to fix this. Thanks much.

**Comment by wjwwood** [comment]
The definitions for rosdep rules are here:

https://github.com/ros/rosdistro/tree/master/rosdep

You can submit a pull request there to change the rule for `fcl` if you think it needs to be changed (seems so to me from your information). You can also change them locally, see: https://docs.ros.org/independent/api/rosdep/html/contributing_rules.html

However, you should ask this on answers.ros.org or in one of the macOS on ROS communities (e.g. https://github.com/mikepurvis/ros-install-osx/issues) for problems like this.

I'll go ahead and close this as it is not an issue with rosdep itself, just the rules it is using by default.
