### ISSUE TITLE
MX Linux not "supported"

### ISSUE THREAD

**Issue by gstavrinos** [ros-infrastructure/rosdep#672]
I think adding support for MX Linux would help quite a lot of people, with MX Linux gaining in popularity everyday. It is Debian based, so it should not be a problem at all. I  am currently running MX Linux 18.1 with ROS Melodic, with no problems.

Thanks,

George

**Comment by tfoote** [comment]
We'd be happy to accept a pull request to add support. 

Note that you'll want to start with an OsDetector in rospkg https://github.com/ros-infrastructure/rospkg/blob/master/src/rospkg/os_detect.py

http://docs.ros.org/independent/api/rospkg/html/developers_guide.html#developing-new-osdetectors

Then you can add an alias entry if it aliases to an ubuntu or debian distribution like here for elementary https://github.com/ros-infrastructure/rosdep/blob/fe63aaac265a2ef3823726250815c0d64e9e9b5c/src/rosdep2/platforms/debian.py#L76

**Comment by gstavrinos** [comment]
Thanks for the guidelines. I will work on it asap.

**Comment by gstavrinos** [comment]
Made the required PRs #674 and ros-infrastructure/rospkg#167.
