### ISSUE TITLE
command-not-found in ubuntu suggests upstream python3-rosdep2 package

### ISSUE THREAD

**Issue by sloretz** [ros-infrastructure/rosdep#763]
It looks like on Ubuntu Focal, bash will suggest `python3-rosdep2` when a user types the command `rosdep`. This is the name of the upstream Debian ackage, but with it users are unable to install `ros-noetic-*` packages.

* It's been decided to not provide a `python3-rosdep2` to hide the upstream ones, since it's not compatible and users should be able to choose between the upstream ROS packages and the `ros-<rosdistro>-` ones even if they have the packages.ros.org apt repo set
* It doesn't just apply to rosdep, but to all executables (catkin_make, rosbash, etc)
* Current idea is to explore adding ROS packages to the command-not-found database. Maybe `ros-environment` or `catkin` could install it?

https://answers.ros.org/question/353082/missing-packages-after-installing-rosdep-based-on-python3-rosdep2-in-noetic/

**Comment by dirk-thomas** [comment]
> It looks like on Ubuntu Focal ...

I would expect this to already be the case in older Ubuntu distros. Since the suggestion comes from what `apt` knowing which Debian package contains an executable with a given name.

**Comment by sloretz** [comment]
> I  would expect this to already be the case in older Ubuntu distros.

Ah sure enough. I hadn't noticed because my containers didn't have `command-not-found` installed. Once I install that I see the same message in a Bionic container.

```console
$ /usr/lib/command-not-found rosdep

Command 'rosdep' not found, but can be installed with:

apt install python-rosdep2
```

**Comment by gavanderhoorn** [comment]
You'll get the notice on every Ubuntu install which has that package installed.

It's been really rather annoying, and I've answered I don't know how many questions by users which have inadvertently followed the advice printed and installed the upstream(ed) packages.

>  * Current idea is to explore adding ROS packages to the command-not-found database. Maybe `ros-environment` or `catkin` could install it?

Is it really a database? I was under the impression it uses something like a reverse `apt` lookup.

**Comment by sloretz** [comment]
> Is it really a database? I was under the impression it uses something like a reverse apt lookup.

No idea. I haven't actually looked into it, but it's the direction I'll be checking first.

**Comment by ReemAlhosainy** [comment]
i too installed python3-rosdep2 and due to that noetic packages were deleted.. is there any step to revert the change or i will have to install ros-noetics again

**Comment by sloretz** [comment]
> i too installed python3-rosdep2 and due to that noetic packages were deleted.. is there any step to revert the change or i will have to install ros-noetics again

You'll have to uninstall that package and reinstall noetic. The following two commands should do it.

```
sudo apt-get remove python3-rosdep2
sudo apt-get install ros-noetic-desktop-full
```

I don't have any plans to try fixing this and it's not really an issue with rosdep, so I'll close this. If someone wants to investigate the source code for the `packagekit-command-not-found` package appears to be here: https://github.com/PackageKit/PackageKit/blob/main/contrib/command-not-found/pk-command-not-found.c
