### ISSUE TITLE
rodep install --ignore-src seems  not working

### ISSUE THREAD

**Issue by oridong** [ros-infrastructure/rosdep#798]
ROS Distro: [Noetic]
OS Version: VMware16.0.0 build-16894299 + Ubuntu 20.04
Source build

> d@ubuntu:~/Robotic/ros_tutorial$ rosdep install --from-paths src/ROS-Academy-for-Beginners  --ignore-src src/ROS-Academy-for-Beginners/robot_sim_demo --rosdistro=noetic
> ERROR: the following packages/stacks could not have their rosdep keys resolved
> to system dependencies:
> robot_sim_demo: Cannot locate rosdep definition for [yocs_cmd_vel_mux]

 robot_sim_dem package should be ignored , but it still report issue for it.

**Comment by emersonknapp** [comment]
This question is more appropriate for `https://answers.ros.org/` - that said, this isn't how the `--ignore-src` option works. Ignore-src will ignore trying to resolve the keys for any packages that exist as source in your specified paths, e.g. it will not try to resolve the key `robot_sim_demo`. If you had `yocs_cmd_vel_mux` in your `--from-paths`, that would also be ignored. If instead you want to "not install dependencies for a given package", then you'll either have to be more selective by providing `--from-paths` that don't include `robot_sim_demo`, or use `--skip-keys` to explicitly skip its dependencies. I often get selective when using colcon by doing something like

```
rosdep install --from-paths $(colcon list --packages-up-to my_package -p) --ignore-src -y
```

If you're using colcon for your workspace, its package selection capabilities can be quite handy for this use case
