### ISSUE TITLE
rosdep install for noetic on macOS asks for GitHub creds for brew tap ros/noetic

### ISSUE THREAD

**Issue by harshitsankhla** [ros-infrastructure/rosdep#801]
Trying to use rosdep to install dependencies for packages in my workspace using - 
rosdep install --from-paths src --ignore-src -r -y

and it asks me to input GitHub credentials - 

Continuing to install resolvable dependencies...
==> Tapping ros/noetic
Cloning into '/usr/local/Homebrew/Library/Taps/ros/homebrew-noetic'...
Username for 'https://github.com':

my creds are not working and gives me repository not found. should I register somewhere to have access to this tap or is there some other way to access an open tap ?

installed ros on macOS using the script from here - https://github.com/smnogar/ros-install-osx

**Comment by HesselM** [comment]
I had the same issue when installing Foxy. Turned out that the repo which brew wanted to install does not exists. 
Unfortunately I do not recall how I solved it.

**Comment by tfoote** [comment]
This doesn't sound like a rosdep bug, but a bug in one of the rosdep rules that the tutorial setups up for you. Please open the ticket there. This tracker is for the source code of rosdep.

**Comment by becschwartz** [comment]
Hello,

What's in your /etc/ros/rosdep/sources.list.d directory?
