### ISSUE TITLE
Bad installer [opkg]: opkg_detect is not implemented yet

### ISSUE THREAD

**Issue by ovaag** [ros-infrastructure/rosdep#833]
When trying `rosdep install --default-yes --ignore-src --from-paths src --skip-keys "px4"`

I get the following error message: 
```
ERROR: Rosdep experienced an internal error.
Please go to the rosdep page [1] and file a bug report with the message below.
[1] : http://www.ros.org/wiki/rosdep

rosdep version: 0.21.0

Bad installer [opkg]: opkg_detect is not implemented yet
```

**Comment by seohwan** [comment]
Hello ovaag,
I faced same issue as yours.
Can you please share how you resolve the issue?
Manty thanks

**Comment by seohwan** [comment]
Hello @ovaag,
I faced same issue as yours.
Can you please share how you resolve the issue?
Manty thanks
