### ISSUE TITLE
[bug] rosdep should ignore build_type

### ISSUE THREAD

**Issue by Aposhian** [ros-infrastructure/rosdep#853]
`package.xml` can mark its build type with `<build_type>ament_python</build_type>`, but when you do this, `rosdep` tries to install `ament_python`, which isn't a valid key. `rosdep` should ignore the `build_type` tag, since it isn't a package to install anyway. It works incidentally for `ament_cmake` packages, since `ament_cmake` _is_ a valid rosdep key.

This makes it so I always have to do `rosdep install --skip-keys ament_python`.

**Comment by cottsay** [comment]
I can't reproduce the behavior you're describing.

Here's my test manifest:
```xml
<package>
  <name>foo</name>
  <version>0.0.0</version>
  <description>foobar</description>
  <maintainer email="ros-orphaned-packages@googlegroups.com">ROS Orphaned Package Maintainers</maintainer>
  <license>Public Domain</license>

  <run_depend>assimp</run_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
```

Here's rosdep:
```
$ rosdep keys --from-path .
assimp
$ rosdep install --from-path . --reinstall -s
#[dnf] Installation commands:
  sudo -H dnf --setopt=strict=0 install assimp
$ rosdep --version
0.20.1
```

**Comment by Aposhian** [comment]
Ok, I just dug a little deeper, and this turned out to be a bug in one of the packages I was pulling in. https://github.com/naoki-mizuno/ds4_driver/pull/27
