### ISSUE TITLE
 Error on Compiling Workspace: No rule to make target '/home/user/anaconda3/lib/libcurl.so', needed by 'devel/lib/libget_file.so'.  Stop.

### ISSUE THREAD

**Issue by JeremyCKT** [ros-infrastructure/rosdep#860]
I followed the instruction here:
https://gitlab.com/autowarefoundation/autoware.ai/autoware/-/wikis/Source-Build

But when I compiling workspace, the error shows as follows:

--- stderr: map_file                                               
make[2]: *** No rule to make target '/home/jeremydl/anaconda3/lib/libcurl.so', needed by 'devel/lib/libget_file.so'.  Stop.
make[1]: *** [CMakeFiles/get_file.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 2
---
Failed   <<< map_file [1.37s, exited with code 2]
Aborted  <<< state_machine_lib [2.03s]
Aborted  <<< autoware_health_checker [5.14s]
Aborted  <<< marker_downsampler [0.17s]
Aborted  <<< astar_search [2.44s]                                            
Aborted  <<< amathutils_lib [2.46s]
Aborted  <<< libvectormap [1.09s]
Aborted  <<< memsic_imu [0.25s]
Aborted  <<< vector_map_server [1.57s]
Aborted  <<< sick_ldmrs_tools [3.01s]              
Aborted  <<< imm_ukf_pda_track [1.31s]
Aborted  <<< object_map [0.57s]                                  

Summary: 36 packages finished [7.97s]
  1 package failed: map_file
  11 packages aborted: amathutils_lib astar_search autoware_health_checker imm_ukf_pda_track libvectormap marker_downsampler memsic_imu object_map sick_ldmrs_tools state_machine_lib vector_map_server
  2 packages had stderr output: autoware_health_checker map_file
  91 packages not processed

What happened on libcurl? How to fix it? Thanks!

**Comment by cottsay** [comment]
This is definitely not the right place to ask about this. If there is a problem with those instructions, consider opening an issue on that repository. If you're having trouble but don't know whether there is a bug or not, consider asking a question on ROS Discourse.

My off-the-cuff guess is that Anaconda could be causing this. Consider disabling your Anaconda environment and trying following the instructions again.
