### ISSUE TITLE
rosdep ignores version specified in package.xml

### ISSUE THREAD

**Issue by rhaschke** [ros-infrastructure/rosdep#896]
`rosdep check` ignores the version specifier in package.xml:
`<run_depend version_gte="0.10.0">franka_description</run_depend>`

Although only franka_description 0.9 is installed:
```
> dpkg -l | grep franka_description
ii  ros-melodic-franka-description                              0.9.0-1bionic.20220831.183028                   amd64        franka_description contains URDF files and meshes of Franka Emika robots
```
rosdep reports no issues:
```
> rosdep check --from-paths . 
All system dependencies have been satisfied
```

**Comment by peci1** [comment]
This is a duplicate of https://github.com/ros-infrastructure/rosdep/issues/325 .
