### ISSUE TITLE
Supporting Fedora Asahi Remix

### ISSUE THREAD

**Issue by peterdavidfagan** [ros-infrastructure/rosdep#939]
I wish to debug and develop ROS 2 code on my MacbookAir with  [Fedora Asahi Remix](https://asahilinux.org/) but currently this aarch-based distribution is not recognised by rosdep. 

Update: I realise this may be more of a `rospkg` issue, as `os_detect` is imported from this package.

**Comment by cottsay** [comment]
> I realise this may more of a `rospkg` issue, as `os_detect` is imported from this package.

Doing it properly requires both. We want `rospkg` to know the difference between Fedora and Fedora Asahi Remix, but as it stands right now, we want `rosdep` to treat both distributions the same since they'll contain the same packages.

**Comment by peterdavidfagan** [comment]
In the interim I got things running by editing the release files (super suboptimal but I wanted to see if drivers worked as expected for GPU). Foxglove + mujoco sim works:

![foxglove_on_mac](https://github.com/ros-infrastructure/rosdep/assets/42982057/a760ada7-bded-4b08-8480-105eee0db227)

**Comment by tfoote** [comment]
For short term workarounds you can use the ROS_OS_OVERRIDE to force the detection or the `--os=` option.
